version: "3.9"

services:
  soundstorm:
    image: xxvladxx/soundstorm:latest
    container_name: soundstorm
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/letsencrypt/live/soundstorm.pp.ua/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/soundstorm.pp.ua/privkey.pem:/certs/privkey.pem:ro
