server {
    listen 80;
    server_name soundstorm.pp.ua www.soundstorm.pp.ua;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name soundstorm.pp.ua www.soundstorm.pp.ua;

    ssl_certificate     /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
