name: Build, push, and deploy soundstorm

on:
  push:
    branches:
      - main
      - pipeline-setup

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t xxvladxx/soundstorm:latest .

      - name: Push Docker image
        run: |
          docker push xxvladxx/soundstorm:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker stop soundstorm || true
            docker rm soundstorm || true

            docker pull xxvladxx/soundstorm:latest

            docker run -d \
              --name soundstorm \
              -p 80:80 \
              -p 443:443 \
              -v /etc/letsencrypt
