
name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            docker pull $DOCKERHUB_REPO:${VERSION_TAG}
            docker rm -f soundstorm || true
            docker run -d \
              --name soundstorm \
              -p 80:80 \
              -p 443:443 \
              -v /etc/letsencrypt/live/soundstorm.pp.ua-0001:/certs/live:ro \
              -v /etc/letsencrypt/archive/soundstorm.pp.ua-0001:/certs/archive:ro \
              $DOCKERHUB_REPO:${VERSION_TAG}
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
          VERSION_TAG: v8

